Web/UnlockMe.Web/Controllers/PostsController.cs
namespace UnlockMe.Web.Controllers
{
    using System;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using UnlockMe.Data.Models;
    using UnlockMe.Services.Data;
    using UnlockMe.Web.ViewModels.Post;

    public class PostsController : Controller
    {
        private readonly IPostService postService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IWebHostEnvironment environment;

        public PostsController(
            IPostService postService,
            UserManager<ApplicationUser> userManager,
            IWebHostEnvironment environment)
        {
            this.postService = postService;
            this.userManager = userManager;
            this.environment = environment;
        }

        [Authorize]
        public IActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(CreatePostInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            var user = await this.userManager.GetUserAsync(this.User);

            try
            {
                var postId = await this.postService.CreateAsync(input, user.Id, $"{this.environment.WebRootPath}/pictures");
                this.TempData["SuccsessfulPostCreateMessage"] = "Your post is successfully created!";
                return this.RedirectToAction(nameof(this.ById), new { id = postId });
            }
            catch (Exception ex)
            {
                this.ModelState.AddModelError(string.Empty, ex.Message);
                return this.View(input);
            }
        }

        // Posts/All/3 "Page of"
        public IActionResult All(int id = 1)
        {
            const int postsPerPage = 6;
            var viewModel = new PostListViewModel
            {
                PostsPerPage = postsPerPage,
                PageNumber = id,
                PostsCount = this.postService.GetCount(),
                Posts = this.postService.GetAll<PostInListViewModel>(id, postsPerPage),
            };
            return this.View(viewModel);
        }

        public IActionResult ById(int id)
        {
            var post = this.postService.GetById<SinglePostViewModel>(id);
            if (post == null)
            {
                return this.NotFound();
            }

            return this.View(post);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Delete(int id)
        {
            await this.postService.DeleteAsync(id);
            return this.RedirectToAction(nameof(this.All));
        }

        public IActionResult CreateSecond()
        {
            return this.View();
        }
    }
}

Web/UnlockMe.Web/Controllers/ProfilesController.cs
namespace UnlockMe.Web.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using UnlockMe.Data;
    using UnlockMe.Data.Models;
    using UnlockMe.Services.Data;
    using UnlockMe.Web.ViewModels.Post;
    using UnlockMe.Web.ViewModels.Profile;

    [Authorize]
    public class ProfilesController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly UserManager<ApplicationUser> userManager;

        public ProfilesController(
            ApplicationDbContext db,
            UserManager<ApplicationUser> userManager)
        {
            this.db = db;
            this.userManager = userManager;
        }

        public async Task<IActionResult> MyProfile()
        {
            var user = await this.userManager.GetUserAsync(this.User);
            var posts = this.db.Posts.Where(p => p.AddedByUserId == user.Id);

            var viewModel = new MyProfileViewModel
            {
                UserName = user.UserName,
                AboutMe = user.AboutMe,
                CreatedOn = user.CreatedOn,
                PostsCount = posts.Count(),
            };

            return this.View(viewModel);
        }
    }
}

Web/UnlockMe.Web/Controllers/QuestionController.cs
namespace UnlockMe.Web.Controllers
{
    using System.Text;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using UnlockMe.Data.Models;
    using UnlockMe.Services.Data;
    using UnlockMe.Services.Messaging;
    using UnlockMe.Web.ViewModels.Question;

    public class QuestionController : Controller
    {
        private readonly IEmailSender emailSender;
        private readonly IQuestionsService questionService;
        private readonly UserManager<ApplicationUser> userManager;

        public QuestionController(
            IEmailSender emailSender,
            IQuestionsService questionService,
            UserManager<ApplicationUser> userManager)
        {
            this.emailSender = emailSender;
            this.questionService = questionService;
            this.userManager = userManager;
        }

        public IActionResult Question()
        {
            return this.View();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Question(CreateQuestionInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            var user = await this.userManager.GetUserAsync(this.User);
            await this.questionService.CreateAsync(input, user.Id);

            // TODO - Redirect to the post view page later
            this.TempData["SuccsessfulQuestionCreateMessage"] = "Your custom question is sent succsessfully! Don't forget to check your email!";
            return this.Redirect("/Question/Question");
        }
    }
}

Web/UnlockMe.Web/Controllers/WalletsController.cs
namespace UnlockMe.Web.Controllers
{
    using System;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using UnlockMe.Data.Common.Repositories;
    using UnlockMe.Data.Models;
    using UnlockMe.Services.Data;

    public class WalletsController : Controller
    {
        private readonly IWalletsService walletsService;
        private readonly UserManager<ApplicationUser> userManager;

        public WalletsController(
            IWalletsService walletsService,
            UserManager<ApplicationUser> userManager)
        {;
            this.walletsService = walletsService;
            this.userManager = userManager;
        }

        public IActionResult MyWallet()
        {
            return this.View();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create()
        {
            var user = await this.userManager.GetUserAsync(this.User);
            var wallet = await this.walletsService.CreateAsync(user.Id);
            this.TempData["SuccessfullyCreatedWalletMessage"] = "Congratulations your wallet is successfully created!";
            this.TempData["SuccessfullyBonusMessage"] = "BONUS: We boost your wallet with 10.99lv and 100 coins!";
            return this.RedirectToAction("MyWallet");
        }
    }
}

Web/UnlockMe.Web/Views/Shared/_Layout.cshtml
@using UnlockMe.Common
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />
    <link href="~/css/style.css" rel="stylesheet" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    <link href="~/lib/fontawesome/css/all.css" rel="stylesheet" asp-append-version="true" />
</head>
<body>
    <div id="wrapper" class="wrapper">
        <header>
            <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@GlobalConstants.SystemName</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <partial name="_LoginPartial" />
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Posts" asp-action="All">All Posts</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Question" asp-action="Question">FAQ</a>
                            </li>
                            @if (this.User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Posts" asp-action="Create">Create Post</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Profiles" asp-action="MyProfile">My Profile</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Wallets" asp-action="MyWallet">Wallet</a>
                                </li>
                            }
                            @if (this.User.IsInRole(GlobalConstants.AdministratorRoleName))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="Administration" asp-controller="Posts" asp-action="Index">Posts ADMIN</a>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <div class="container">
            <partial name="_CookieConsentPartial" />
            <main role="main" class="pb-3">
                @this.RenderBody()
            </main>
        </div>
        <footer class="ranna-bg-dark">
            <div class="container">
                &copy; @DateTime.Now.Year - @GlobalConstants.SystemName - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    @await this.RenderSectionAsync("Scripts", required: false)
</body>
</html>